#!/bin/bash
t_support="3"
t_confidence="65"
bitcode=''

if [[ $# -eq 1 ]]; then
    bitcode="$1"
elif [[ $# -eq 3 ]]; then
    bitcode="$1"
    t_support="$2"
    t_confidence="$3"
else
    echo "Wrong number of arguments"
    exit 1
fi

opt -print-callgraph $bitcode 2>&1 >/dev/null | ../partA $t_support $t_confidence | sort
